version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: teste
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: teste
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: